spring:
  datasource:
    url: jdbc:mysql://192.168.233.132:3306/mybatis?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: liuyin
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      connection-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
debug: false
